### ISSUE TITLE
No readme file

### ISSUE THREAD

**Issue by antoniolocandro** [OpenAviationMap/rendering#2]
Please provide a **Readme** file

**Comment by akosmaroy** [comment]
valid point. currently our documentation is going through migration, but you can see some pointers here: https://code.google.com/p/openaviationmap/wiki/HowToInstallServer  - which is the old location, and will be replaced with our own wiki

**Comment by molysgaard** [comment]
This is resolved with 5b3fe98b710da844b548e20388417ebdcd6879ab
